/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.View;

/**
 *
 * @author User
 */
public class Modificar extends javax.swing.JPanel {

    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        TContainer = new javax.swing.JPanel();
        TContainer1 = new javax.swing.JPanel();
        TContainer2 = new javax.swing.JPanel();
        TContainer3 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        ContainerLateral = new javax.swing.JPanel();
        ContainerLateral1 = new javax.swing.JPanel();
        ContainerLateral2 = new javax.swing.JPanel();
        BtnRegistrar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnListas = new javax.swing.JButton();
        BtnProximamente = new javax.swing.JButton();
        AreaPrinicipal = new javax.swing.JPanel();
        AP1 = new javax.swing.JPanel();
        AP2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaReservas = new javax.swing.JTable();

        Fondo.setBackground(new java.awt.Color(0, 25, 128));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/logoxue.png"))); // NOI18N

        TContainer.setBackground(new java.awt.Color(0, 25, 128));
        TContainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        TContainer1.setBackground(new java.awt.Color(255, 0, 0));
        TContainer1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        TContainer2.setBackground(new java.awt.Color(0, 51, 255));
        TContainer2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        TContainer3.setBackground(new java.awt.Color(100, 153, 255));
        TContainer3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Titulo.setText("LABORATORIO MARKETING");

        javax.swing.GroupLayout TContainer3Layout = new javax.swing.GroupLayout(TContainer3);
        TContainer3.setLayout(TContainer3Layout);
        TContainer3Layout.setHorizontalGroup(
            TContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TContainer3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        TContainer3Layout.setVerticalGroup(
            TContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TContainer3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TContainer2Layout = new javax.swing.GroupLayout(TContainer2);
        TContainer2.setLayout(TContainer2Layout);
        TContainer2Layout.setHorizontalGroup(
            TContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TContainer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TContainer2Layout.setVerticalGroup(
            TContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TContainer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TContainer1Layout = new javax.swing.GroupLayout(TContainer1);
        TContainer1.setLayout(TContainer1Layout);
        TContainer1Layout.setHorizontalGroup(
            TContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        TContainer1Layout.setVerticalGroup(
            TContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TContainerLayout = new javax.swing.GroupLayout(TContainer);
        TContainer.setLayout(TContainerLayout);
        TContainerLayout.setHorizontalGroup(
            TContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TContainerLayout.setVerticalGroup(
            TContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ContainerLateral.setBackground(new java.awt.Color(0, 50, 150));
        ContainerLateral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        ContainerLateral1.setBackground(new java.awt.Color(255, 0, 0));
        ContainerLateral1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        ContainerLateral2.setBackground(new java.awt.Color(0, 50, 255));
        ContainerLateral2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        BtnRegistrar.setBackground(new java.awt.Color(100, 153, 255));
        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnRegistrar.setText("Registrar Reserva");
        BtnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        BtnModificar.setBackground(new java.awt.Color(100, 153, 255));
        BtnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnModificar.setText("Modificar Reserva");
        BtnModificar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        BtnListas.setBackground(new java.awt.Color(100, 153, 255));
        BtnListas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnListas.setText("Registro de Reservas");
        BtnListas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        BtnProximamente.setBackground(new java.awt.Color(100, 153, 255));
        BtnProximamente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnProximamente.setText("Proximamente");
        BtnProximamente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout ContainerLateral2Layout = new javax.swing.GroupLayout(ContainerLateral2);
        ContainerLateral2.setLayout(ContainerLateral2Layout);
        ContainerLateral2Layout.setHorizontalGroup(
            ContainerLateral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLateral2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContainerLateral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnListas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnProximamente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ContainerLateral2Layout.setVerticalGroup(
            ContainerLateral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLateral2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnListas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnProximamente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ContainerLateral1Layout = new javax.swing.GroupLayout(ContainerLateral1);
        ContainerLateral1.setLayout(ContainerLateral1Layout);
        ContainerLateral1Layout.setHorizontalGroup(
            ContainerLateral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLateral1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContainerLateral2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContainerLateral1Layout.setVerticalGroup(
            ContainerLateral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLateral1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContainerLateral2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ContainerLateralLayout = new javax.swing.GroupLayout(ContainerLateral);
        ContainerLateral.setLayout(ContainerLateralLayout);
        ContainerLateralLayout.setHorizontalGroup(
            ContainerLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContainerLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContainerLateralLayout.setVerticalGroup(
            ContainerLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContainerLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        AreaPrinicipal.setBackground(new java.awt.Color(0, 50, 155));
        AreaPrinicipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        AP1.setBackground(new java.awt.Color(255, 0, 0));
        AP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        AP2.setBackground(new java.awt.Color(0, 50, 255));
        AP2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        TablaReservas.setBackground(new java.awt.Color(100, 153, 255));
        TablaReservas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        TablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Equipo", "ID Usuario", "Equipo", "Tipo", "Ubicación", "Horas Reservadas", "Fecha Reservación"
            }
        ));
        TablaReservas.setToolTipText("");
        TablaReservas.setFocusable(false);
        TablaReservas.setGridColor(new java.awt.Color(0, 0, 0));
        TablaReservas.setInheritsPopupMenu(true);
        TablaReservas.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TablaReservas.setShowGrid(true);
        jScrollPane2.setViewportView(TablaReservas);

        javax.swing.GroupLayout AP2Layout = new javax.swing.GroupLayout(AP2);
        AP2.setLayout(AP2Layout);
        AP2Layout.setHorizontalGroup(
            AP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        AP2Layout.setVerticalGroup(
            AP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout AP1Layout = new javax.swing.GroupLayout(AP1);
        AP1.setLayout(AP1Layout);
        AP1Layout.setHorizontalGroup(
            AP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AP1Layout.setVerticalGroup(
            AP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout AreaPrinicipalLayout = new javax.swing.GroupLayout(AreaPrinicipal);
        AreaPrinicipal.setLayout(AreaPrinicipalLayout);
        AreaPrinicipalLayout.setHorizontalGroup(
            AreaPrinicipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaPrinicipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AreaPrinicipalLayout.setVerticalGroup(
            AreaPrinicipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaPrinicipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContainerLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AreaPrinicipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ContainerLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AreaPrinicipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AP1;
    private javax.swing.JPanel AP2;
    private javax.swing.JPanel AreaPrinicipal;
    private javax.swing.JButton BtnListas;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnProximamente;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JPanel ContainerLateral;
    private javax.swing.JPanel ContainerLateral1;
    private javax.swing.JPanel ContainerLateral2;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JPanel TContainer;
    private javax.swing.JPanel TContainer1;
    private javax.swing.JPanel TContainer2;
    private javax.swing.JPanel TContainer3;
    private javax.swing.JTable TablaReservas;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
